###
GET http://{{host}}/v1/index/200

###
POST http://{{host}}/v1/index/200
Content-Type: application/json

{
  "code": "TEST1",
  "message": "메시지"
}

###
PUT http://{{host}}/v1/index/200
Content-Type: application/json

{
  "code": "TEST1",
  "message": "메시지"
}

###
DELETE http://{{host}}/v1/index/200
Content-Type: application/json

{
  "code": "TEST1",
  "message": "메시지"
}

###
GET http://{{host}}/v1/users/TestId
